export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOAD_USER = "LOAD_USER";

export const FORM_DATA = "FORM_DATA";
export const FORM_DELETE = "FORM_DELETE";

export const ADD_DATA_LOADING = "ADD_DATA_LOADING";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_ERROR = "ADD_DATA_ERROR";
export const CLEAR_ADD_DATA_ERROR = "CLEAR_ADD_DATA_ERROR";

export const FETCH_DATA_LOADING = "FETCH_DATA_LOADING";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";

export const FETCH_DATA_SUCCESS_NEWS = "FETCH_DATA_SUCCESS_NEWS";
export const FETCH_DATA_NEWS_DETAIL = "FETCH_DATA_NEWS_DETAIL";

export const FETCH_DATA_SUCCESS_MEMBERS = "FETCH_DATA_SUCCESS_MEMBERS";
//export const FETCH_DATA_SUCCESS_SATGAS = "FETCH_DATA_SUCCESS_SATGAS";

export const FETCH_DATA_SETTING = "FETCH_DATA_SETTING";
export const CHG_PROPS = "CHG_PROPS";